-- Script was generated by Devart Entity Developer, Version 6.7.965.0
-- Script date 10/27/2025 1:48:00 PM
-- Target Server: PostgreSQL
-- Server Version: 12.0

-- 
-- Creating a table "AspNetUsers" 
-- 
CREATE TABLE "AspNetUsers" (
   "Id" VARCHAR(450) NOT NULL,
   "UserName" VARCHAR(256),
   "NormalizedUserName" VARCHAR(256),
   "Email" VARCHAR(256),
   "NormalizedEmail" VARCHAR(256),
   "EmailConfirmed" BOOLEAN NOT NULL,
   "PasswordHash" TEXT,
   "SecurityStamp" TEXT,
   "ConcurrencyStamp" TEXT,
   "PhoneNumber" TEXT,
   "PhoneNumberConfirmed" BOOLEAN NOT NULL,
   "TwoFactorEnabled" BOOLEAN NOT NULL,
   "LockoutEnd" TIMESTAMPTZ,
   "LockoutEnabled" BOOLEAN NOT NULL,
   "AccessFailedCount" INT NOT NULL,
   CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
   CONSTRAINT "KEY_AspNetUsers_NormalizedUserName" UNIQUE ("NormalizedUserName")
);

-- 
-- Creating a table "AspNetRoles" 
-- 
CREATE TABLE "AspNetRoles" (
   "Id" VARCHAR(450) NOT NULL,
   "Name" VARCHAR(256),
   "NormalizedName" VARCHAR(256),
   "ConcurrencyStamp" TEXT,
   CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id"),
   CONSTRAINT "KEY_AspNetRoles_NormalizedName" UNIQUE ("NormalizedName")
);

-- 
-- Creating a table "AspNetUserTokens" 
-- 
CREATE TABLE "AspNetUserTokens" (
   "UserId" VARCHAR(450) NOT NULL,
   "LoginProvider" VARCHAR(450) NOT NULL,
   "Name" VARCHAR(450) NOT NULL,
   "Value" TEXT,
   CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
   CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_0" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id")
);

-- 
-- Creating a table "AspNetUserLogins" 
-- 
CREATE TABLE "AspNetUserLogins" (
   "LoginProvider" VARCHAR(450) NOT NULL,
   "ProviderKey" VARCHAR(450) NOT NULL,
   "ProviderDisplayName" TEXT,
   "UserId" VARCHAR(450) NOT NULL,
   CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
   CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_0" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id")
);

-- 
-- Creating a table "AspNetRoleClaims" 
-- 
CREATE TABLE "AspNetRoleClaims" (
   "Id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "RoleId" VARCHAR(450) NOT NULL,
   "ClaimType" TEXT,
   "ClaimValue" TEXT,
   CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
   CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_0" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id")
);

-- 
-- Creating a table "AspNetUserClaims" 
-- 
CREATE TABLE "AspNetUserClaims" (
   "Id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "UserId" VARCHAR(450) NOT NULL,
   "ClaimType" TEXT,
   "ClaimValue" TEXT,
   CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
   CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_0" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id")
);

-- 
-- Creating a table "AspNetUserRoles" 
-- 
CREATE TABLE "AspNetUserRoles" (
   "UserId" VARCHAR(450) NOT NULL,
   "RoleId" VARCHAR(450) NOT NULL,
   CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
   CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_0" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id"),
   CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_1" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id")
);

