-- Script was generated by Devart Entity Developer, Version 6.7.965.0
-- Script date 10/27/2025 1:39:53 PM
-- Target Server: PostgreSQL
-- Server Version: 12.0

-- 
-- Creating a table dbo."AspNetUsers" 
-- 
CREATE TABLE dbo."AspNetUsers" (
   "Id" NVARCHAR NOT NULL,
   "UserName" NVARCHAR,
   "NormalizedUserName" NVARCHAR,
   "Email" NVARCHAR,
   "NormalizedEmail" NVARCHAR,
   "EmailConfirmed" BIT NOT NULL,
   "PasswordHash" NVARCHAR(MAX),
   "SecurityStamp" NVARCHAR(MAX),
   "ConcurrencyStamp" NVARCHAR(MAX),
   "PhoneNumber" NVARCHAR(MAX),
   "PhoneNumberConfirmed" BIT NOT NULL,
   "TwoFactorEnabled" BIT NOT NULL,
   "LockoutEnd" DATETIMEOFFSET,
   "LockoutEnabled" BIT NOT NULL,
   "AccessFailedCount" INT NOT NULL,
   CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
   CONSTRAINT "KEY_AspNetUsers_NormalizedUserName" UNIQUE ("NormalizedUserName")
);

-- 
-- Creating a table dbo."AspNetRoles" 
-- 
CREATE TABLE dbo."AspNetRoles" (
   "Id" NVARCHAR NOT NULL,
   "Name" NVARCHAR,
   "NormalizedName" NVARCHAR,
   "ConcurrencyStamp" NVARCHAR(MAX),
   CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id"),
   CONSTRAINT "KEY_AspNetRoles_NormalizedName" UNIQUE ("NormalizedName")
);

-- 
-- Creating a table dbo."AspNetUserTokens" 
-- 
CREATE TABLE dbo."AspNetUserTokens" (
   "UserId" NVARCHAR NOT NULL,
   "LoginProvider" NVARCHAR NOT NULL,
   "Name" NVARCHAR NOT NULL,
   "Value" NVARCHAR(MAX),
   CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
   CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_0" FOREIGN KEY ("UserId") REFERENCES dbo."AspNetUsers" ("Id")
);

-- 
-- Creating a table dbo."AspNetUserLogins" 
-- 
CREATE TABLE dbo."AspNetUserLogins" (
   "LoginProvider" NVARCHAR NOT NULL,
   "ProviderKey" NVARCHAR NOT NULL,
   "ProviderDisplayName" NVARCHAR(MAX),
   "UserId" NVARCHAR NOT NULL,
   CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
   CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_0" FOREIGN KEY ("UserId") REFERENCES dbo."AspNetUsers" ("Id")
);

-- 
-- Creating a table dbo."AspNetRoleClaims" 
-- 
CREATE TABLE dbo."AspNetRoleClaims" (
   "Id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "RoleId" NVARCHAR NOT NULL,
   "ClaimType" NVARCHAR(MAX),
   "ClaimValue" NVARCHAR(MAX),
   CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
   CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_0" FOREIGN KEY ("RoleId") REFERENCES dbo."AspNetRoles" ("Id")
);

-- 
-- Creating a table dbo."AspNetUserClaims" 
-- 
CREATE TABLE dbo."AspNetUserClaims" (
   "Id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "UserId" NVARCHAR NOT NULL,
   "ClaimType" NVARCHAR(MAX),
   "ClaimValue" NVARCHAR(MAX),
   CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
   CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_0" FOREIGN KEY ("UserId") REFERENCES dbo."AspNetUsers" ("Id")
);

-- 
-- Creating a table dbo."AspNetUserRoles" 
-- 
CREATE TABLE dbo."AspNetUserRoles" (
   "UserId" NVARCHAR NOT NULL,
   "RoleId" NVARCHAR NOT NULL,
   CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
   CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_0" FOREIGN KEY ("RoleId") REFERENCES dbo."AspNetRoles" ("Id"),
   CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_1" FOREIGN KEY ("UserId") REFERENCES dbo."AspNetUsers" ("Id")
);

